# 
# Do not Edit! Generated by:
# spectacle version 0.13~pre
# 
# >> macros
# << macros

Name:       patch
Summary:    The GNU patch command, for modifying/upgrading files
Version:    2.6.1
Release:    35
Group:      Development/Tools
License:    GPLv3
URL:        http://www.gnu.org/software/patch/patch.html
Source0:    ftp://ftp.gnu.org/gnu/patch/patch-%{version}.tar.xz
Source100:  patch.yaml
Patch0:     patch-2.5.4-sigsegv.patch

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
The patch program applies diff files to originals.  The diff command
is used to compare an original to a changed file.  Diff lists the
changes made to the file.  A person who has the original file can then
use the patch command with the diff file to add the changes to their
original file (patching the file).

Patch should be installed because it is a common way of upgrading
applications.




%prep
%setup -q -n %{name}-%{version}
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
CFLAGS="$RPM_OPT_FLAGS -D_GNU_SOURCE"
# << build pre

%configure --disable-static
# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post


# << install post

%clean
rm -rf %{buildroot}






%files
%defattr(-,root,root,-)
# >> files
%doc NEWS README
%{_bindir}/*
%doc %{_mandir}/*/*
# << files


